### ISSUE TITLE
Race condition on first startup

### ISSUE THREAD

**Issue by chrisys** [balenablocks/transport#2]
If the transport primitive starts before InfluxDB the database creation times out and is not retried.

![Screenshot 2020-07-24 at 16 56 32](https://user-images.githubusercontent.com/521698/88410721-a1384d00-cdce-11ea-89a8-e08855e700bc.png)

**Comment by phil-d-wilson** [comment]
I wonder if there is much we can do here, other than using "depends_on" in your docker compose for the transport service?!?

**Comment by phil-d-wilson** [comment]
Tested "depends_on" in docker compose, but that doesn't cause transport to wait until the InfluxDB server has started running - only that the service is running. Might need to look into other options of polling certain outputs to find when they are genuinely up, before even starting telegraf.

**Comment by phil-d-wilson** [comment]
I can't recreate this so far. My tests steps:

1. Stop InfluxDB
2. Change the name of the target DB in transport with the `INFLUXDB_DB` variable
3. Watch transport failing to write to new DB
4. Wait <=5 minutes
5. Start InfluxDB

This resulted in telegraf continuing to try and write to the DB (as sensor data kept coming in) until it eventually succeeded.

My hunch is that @chrisys did not have a valid data source (issue #3 solves this) and therefore telegraf wasn't continuously prompted to try and create the DB. With a valid source, I think this will work as expected.

**Comment by phil-d-wilson** [comment]
Closing as I can't recreate this, as long as you have a valid data source.
